apiVersion: v1
kind: Service
metadata:
  labels:
    app: catalogue-db
    name: catalogue-db
    version: v0.1.0
  name: catalogue-db
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: catalogue-db
    name: catalogue-db
    version: v0.1.0
