apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-db
    name: user-db
    version: v0.1.0
  name: user-db
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: user-db
    name: user-db
    version: v0.1.0
