apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-sockshop

resources:
- carts-db.yaml
- carts.yaml
- catalog-db.yaml
- catalog.yaml
- frontend.yaml
- orders-db.yaml
- orders.yaml
- payment.yaml
- queue.yaml
- rabbitmq.yaml
- session.yaml
- shipping.yaml
- user-db.yaml
- user.yaml
